### ISSUE TITLE
Pdf conversion process breaks for some reason

### ISSUE THREAD

**Issue by Zanzibar82** [pviotti/issuu-pdf-dl#8] opened 2022-08-30 14:03 UTC
The script successfully creates a temporary folder and manages to get .jpgs from host, but breaks halfway the process of converting each jpg to pdf. 

An first extract of the error:

`...

2022-08-30 15:49:57 - Downloaded: page_223.jpg
2022-08-30 15:49:58 - Downloaded: page_224.jpg
2022-08-30 15:49:58 - All pages have been downloaded.
Error converting /tmp/d20220830-6822-11bnqm7/page_105.jpg to PDF.
Error converting /tmp/d20220830-6822-11bnqm7/page_106.jpg to PDF.

...`

The book is 224 pages, all files gets created successfully in temporary folder, checked real-time from nautilus.
The page_105.jpg file is there and is working fine, doesn't even seem corrupted. Output at the end is as follows:

`...

Error converting /tmp/d20220830-6822-11bnqm7/page_221.jpg to PDF.
Error converting /tmp/d20220830-6822-11bnqm7/page_222.jpg to PDF.
Error converting /tmp/d20220830-6822-11bnqm7/page_223.jpg to PDF.
Error converting /tmp/d20220830-6822-11bnqm7/page_224.jpg to PDF.
Error: Unable to find file.
Error: Failed to open PDF file:
   /tmp/d20220830-6822-11bnqm7/page_105.jpg.pdf
Errors encountered.  No output created.
Done.  Input errors, so no output created.

...`

Seems to me that the temporary folder gets deleted while task is running, so it breaks halfway. I know it sounds crazy.

Link I have this error is [here](https://issuu.com/euraniecryzz/docs/a_il_guardiano_degli_innocenti_-_an)

Thanks in advance for support.

**Comment by pviotti** [comment] 2022-09-05 08:10
Sorry I can't reproduce the problem, here it works fine:
```bash
2022-09-05 08:53:03 - Downloaded: page_221.jpg
2022-09-05 08:53:03 - Downloaded: page_222.jpg
2022-09-05 08:53:04 - Downloaded: page_223.jpg
2022-09-05 08:53:04 - Downloaded: page_224.jpg
2022-09-05 08:53:04 - All pages have been downloaded.
2022-09-05 08:53:19 - a_il_guardiano_degli_innocenti_-_an.pdf has been created successfully.
```
From your log it seems it cannot convert the single JPG pages to PDF. Maybe you could try converting them manually by doing the following:
1. comment out lines 37-42 of the script, so it just tries to convert the pages to PDFs and doesn't remove the temp folder
2. run the script
3. try to convert manually the pages on which you got an error using ImageMagick CLI tool `convert`: `convert <page.jpg> <page.pdf>`

fyi I'm using ImageMagick v7.1.0-47 and its Ruby bindings are [v4.2.6-1](https://aur.archlinux.org/packages/ruby-rmagick).

**Comment by pviotti** [comment] 2023-07-02 19:19
Closing this issue, as the tool has been rewritten in Python so there isn't any ImageMagick-related dependency anymore.

**Closed as completed by pviotti** 2023-07-02 19:19 UTC
